version: 0.0
os: linux
files:
  - source: hello-0.0.1-SNAPSHOT.jar
    destination: /tmp/codedeploy-deployment-staging-area/
hooks:
  ApplicationStop:
    - location: application_stop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: application_conf.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: root