version: 0.0
os: linux
files:
  - source: /
    destination: /app/hello
hooks:
#  ApplicationStop:
#    - location: application_stop.sh
#      timeout: 300
#      runas: root
  AfterInstall:
    - location: application_conf.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
      runas: root